### ISSUE TITLE
console.log silent, but create a log with a python logging package. See note.

### ISSUE THREAD

**Issue by kristinbell** [TeamDelightful/GlassPlateGame#136]
FROM BART: Honestly, I'd prefer the console log being completely silent: I'd suggest using a Python logging package that logs to a file or whatever in a standard format. Useful information would be game creation and termination times, participant join / leave times and IPs, game IDs. That would give us some tools in case there were issues.

**Comment by BartMassey** [comment]
Thanks much! Only change I'd improve is to make logged IP addresses part of other log lines rather than standalone, so that they're connected to the thing they're the address of.

**Comment by kristinbell** [comment]
Okay, let me see if I can get it to do that. Thanks for the feedback!

**Comment by kristinbell** [comment]
Okay, got it fixed. Should be working now.

**Comment by BartMassey** [comment]
Big improvement, thanks! Some issues still outstanding (shall I file new Issues?):

* Please remove `gpgLog.log` from the repo
* Some log messages are being printed twice
* Extraneous blank lines in log (probably newline plus `console.log()` or similar)
* Looks from the log like player number is being incremented twice?

Sample log (commit 9a215ee859b00b451f566ad88fc81aaffc808a23):

```text
22-Nov-21 10:43:01 AM - INFO - Added game: 28CSX to game pages.
22-Nov-21 10:43:01 AM - INFO - Host IP address: 75.145.68.91

22-Nov-21 10:43:01 AM - INFO - Player 3 named Bart in game 28CSX joining with IP address: 75.145.68.91

22-Nov-21 10:43:01 AM - INFO - Player 5 named Bart 2 in game 28CSX joining with IP address: 75.145.68.91

22-Nov-21 10:43:01 AM - INFO - Player 3 in game 28CSX exiting with IP address: 75.145.68.91

22-Nov-21 10:43:01 AM - INFO - Player 3 in game 28CSX exiting with IP address: 75.145.68.91

22-Nov-21 10:43:01 AM - INFO - Player 5 in game 28CSX exiting with IP address: 75.145.68.91

22-Nov-21 10:43:01 AM - INFO - Player 5 in game 28CSX exiting with IP address: 75.145.68.91

```

**Comment by kristinbell** [comment]
Thanks. I'll just open the issue back up. I think I got it to ignore the log file for the repo. Will work on other stuff soon.

**Comment by kristinbell** [comment]
I got the extra spaces taken out, but I can't recreate the duplication issue. Are you still having that issue????

**Comment by BartMassey** [comment]
Yep, still dupes.

```text
25-Nov-21 10:01:33 PM - INFO - Added game: WQGPF to game pages.
25-Nov-21 10:01:33 PM - INFO - Host with game WQGPF has IP address: 75.145.68.91
25-Nov-21 10:01:33 PM - INFO - Player 2 named A in game WQGPF joining with IP ad
dress: 75.145.68.91
25-Nov-21 10:01:33 PM - INFO - Player 3 named B in game WQGPF joining with IP ad
dress: 75.145.68.91
25-Nov-21 10:01:33 PM - INFO - Player 2 in game WQGPF exiting with IP address: 7
5.145.68.91
25-Nov-21 10:01:33 PM - INFO - Player 2 in game WQGPF exiting with IP address: 7
5.145.68.91
25-Nov-21 10:01:33 PM - INFO - Got index of game WQGPF from array: 0. Can delete
 page.
25-Nov-21 10:01:33 PM - INFO - Player 3 in game WQGPF exiting with IP address: 7
5.145.68.91
25-Nov-21 10:01:33 PM - INFO - Player 3 in game WQGPF exiting with IP address: 7
5.145.68.91
```

**Comment by kristinbell** [comment]
Ooof. I’ll try to find that bug.

**Comment by kristinbell** [comment]
Bart, I moved the function that calls the exiting with IP address, and I can't get it to recreate that duplication error, but I wasn't really getting that error before. I just updated the repo. Can you try this version and if it is still happening, can you tell me 1) which browser you are using 2) mobile or desktop 3) are you exiting with the leave button or just closing the window 4) anything else you think is relevant. Thanks for your help. Sorry I'm having trouble getting this error to happen on my end.

**Comment by BartMassey** [comment]
Still repeats I'm afraid.

```text
27-Nov-21 10:58:55 PM - INFO - Added game: 17NSI to game pages.
27-Nov-21 10:58:55 PM - INFO - Host with game 17NSI has IP address: 75.145.68.91
27-Nov-21 10:58:55 PM - INFO - Player 2 named Bart in game 17NSI joining with IP address: 75.145.68.91
27-Nov-21 10:58:55 PM - INFO - Player 3 named Also Bart in game 17NSI joining with IP address: 75.145.68.91
27-Nov-21 10:58:55 PM - INFO - Player 3 in game 17NSI exiting with IP address: 75.145.68.91
27-Nov-21 10:58:55 PM - INFO - Player 3 in game 17NSI exiting with IP address: 75.145.68.91
27-Nov-21 10:58:55 PM - INFO - Got index of game 17NSI from array: 0. Can delete page.
27-Nov-21 10:58:55 PM - INFO - Player 2 in game 17NSI exiting with IP address: 75.145.68.91
```
Google Chrome on Linux desktop; exiting via leave button; leaving second player then leaving creating player.

Sorry this is turning out tough to debug.

**Comment by kristinbell** [comment]
Oh okay. Thank you! With that breakdown I think I've figured out why it is happening. Thanks so much! Now just have to fix it.

**Comment by kristinbell** [comment]
I think I've got it sorted now. Should work. Let me know if you have any issues and I'll reopen this issue.

**Comment by BartMassey** [comment]
Looks like that's got it. Thanks!
